### ISSUE TITLE
页面引入之后组件报错

### ISSUE THREAD

**Issue by wekerSnail** [jianhao/taro-canvas#1]
```
 Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.
```
![image](https://user-images.githubusercontent.com/30314164/136887249-8866825b-e0ab-443b-86c1-2b604bccc577.png)

**Comment by jianhao** [comment]
把你的绘图配置提供一下，你的图片链接好像有点问题

**Comment by wekerSnail** [comment]
问题我已经解决了，应该就是我提的第二个issue导致的，另外我还遇到一个比较奇怪的问题，部分手机会无法绘制海报，但是打开手机的调试就正常了，关闭就不行，真机调试也可以正常，

**Comment by wekerSnail** [comment]
已解决，是部分来自微信的老数据是http导致的
